---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "comment.fullname" . }}
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: ui-ingress
  backend:
    serviceName: {{ template "comment.fullname" . }}
    servicePort: {{ .Values.service.externalPort }}
