- hosts: master
  become: yes
  tasks:
    - debug: var=ansible_host
    - name: initialize the cluster
      #shell: kubeadm init --pod-network-cidr=10.244.0.0/16 --apiserver-cert-extra-sans={{ ansible_host }} --apiserver-advertise-address={{ ansible_host }} --control-plane-endpoint={{ ansible_host }} >> cluster_initialized.txt
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: create .kube directory
      become: yes
      become_user: ubuntu
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/ubuntu/.kube/config
        owner: ubuntu
        remote_src: yes

    - name: copy kube admin.conf to local
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: kube-admin.conf

    - name: coping calico template
      become: yes
      become_user: ubuntu
      template:
        src: calico.yaml.j2
        dest: $HOME/calico.yaml
        owner: ubuntu

    - name: install calico network
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f $HOME/calico.yaml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
